services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: signbox-list-pusher-tg-bot
    container_name: signbox-list-pusher-tg-bot
    restart: unless-stopped
    env_file:
      - .env
    profiles:
      - prod

  bot-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: signbox-list-pusher-tg-bot-dev
    container_name: signbox-list-pusher-tg-bot-dev
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env:ro
    environment:
      CHOKIDAR_USEPOLLING: "true"
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
        - action: restart
          path: ./.env
        - action: rebuild
          path: package.json
        - action: rebuild
          path: yarn.lock
    profiles:
      - dev
